import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { PencilLine } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

export function CitationEditorPanel() {
  const projects = trpc.content.list.useQuery(); const [projectId, setProjectId] = useState(""); const id = Number(projectId); const citations = trpc.content.citations.useQuery({ contentProjectId: id }, { enabled: !!id }); const [citationId, setCitationId] = useState(""); const selected = citations.data?.find(item => String(item.id) === citationId); const [claim, setClaim] = useState(""); const [citationText, setCitationText] = useState("");
  useEffect(() => { if (!projectId && projects.data?.[0]) setProjectId(String(projects.data[0].id)); }, [projectId, projects.data]); useEffect(() => { if (!citationId && citations.data?.[0]) setCitationId(String(citations.data[0].id)); }, [citationId, citations.data]); useEffect(() => { if (selected) { setClaim(selected.claim); setCitationText(selected.citationText); } }, [selected?.id]);
  const update = trpc.content.updateCitation.useMutation({ onSuccess: async () => { await citations.refetch(); toast.success("Citation updated."); }, onError: error => toast.error(error.message) });
  return <Card className="blueprint-card border-0"><CardContent className="space-y-4 p-5"><div><p className="eyebrow">CITATION EDITOR</p><p className="mt-2 text-sm text-slate-600">Revise a section-attributed citation without changing its owner or publishing content.</p></div><div className="grid gap-3 md:grid-cols-2"><Select value={projectId} onValueChange={value => { setProjectId(value); setCitationId(""); }}><SelectTrigger><SelectValue placeholder="Select project" /></SelectTrigger><SelectContent>{projects.data?.map(project => <SelectItem key={project.id} value={String(project.id)}>{project.title}</SelectItem>)}</SelectContent></Select><Select value={citationId} onValueChange={setCitationId} disabled={!citations.data?.length}><SelectTrigger><SelectValue placeholder="Select citation" /></SelectTrigger><SelectContent>{citations.data?.map(item => <SelectItem key={item.id} value={String(item.id)}>{item.section} · {item.claim.slice(0, 42)}</SelectItem>)}</SelectContent></Select></div>{selected ? <><Textarea value={claim} onChange={event => setClaim(event.target.value)} /><Textarea value={citationText} onChange={event => setCitationText(event.target.value)} /><Button disabled={update.isPending || claim.trim().length < 2 || citationText.trim().length < 2} onClick={() => update.mutate({ contentProjectId: id, citationId: selected.id, section: selected.section, locator: selected.locator || undefined, claim, citationText, sourceId: selected.sourceId || undefined })}><PencilLine className="mr-2 size-4" />Save citation revision</Button></> : <div className="rounded-xl border border-dashed border-slate-200 p-5 text-center text-sm text-slate-500">Record a citation before editing it.</div>}</CardContent></Card>;
}
