import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { FileText } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

const stages = ["research", "outline", "script", "storyboard", "production", "review", "exported"] as const;

export function ContentArtifactPanel() {
  const projects = trpc.content.list.useQuery();
  const [projectId, setProjectId] = useState("");
  const [outline, setOutline] = useState(""); const [script, setScript] = useState(""); const [storyboard, setStoryboard] = useState(""); const [exportNotes, setExportNotes] = useState(""); const [tags, setTags] = useState(""); const [stage, setStageValue] = useState<(typeof stages)[number]>("research");
  const selected = projects.data?.find(project => String(project.id) === projectId);
  useEffect(() => { if (!projectId && projects.data?.[0]) setProjectId(String(projects.data[0].id)); }, [projectId, projects.data]);
  useEffect(() => { const metadata = (selected?.metadata ?? {}) as Record<string, unknown>; setOutline(typeof metadata.outline === "string" ? metadata.outline : ""); setScript(typeof metadata.script === "string" ? metadata.script : ""); setStoryboard(typeof metadata.storyboard === "string" ? metadata.storyboard : ""); setExportNotes(typeof metadata.exportNotes === "string" ? metadata.exportNotes : ""); setTags(Array.isArray(metadata.tags) ? metadata.tags.filter(tag => typeof tag === "string").join(", ") : ""); if (selected) setStageValue(selected.stage); }, [selected?.id]);
  const updateArtifacts = trpc.content.updateArtifacts.useMutation({ onSuccess: async () => { await projects.refetch(); toast.success("Content artifacts saved."); }, onError: error => toast.error(error.message) });
  const updateStage = trpc.content.setStage.useMutation({ onSuccess: async () => { await projects.refetch(); toast.success("Content lifecycle stage updated."); }, onError: error => toast.error(error.message) });
  const busy = updateArtifacts.isPending || updateStage.isPending;
  return <Card className="blueprint-card border-0"><CardContent className="space-y-4 p-5"><div><p className="eyebrow">CONTENT ARTIFACT WORKSPACE</p><p className="mt-2 text-sm leading-6 text-slate-600">Keep source-backed outlines, scripts, storyboards, metadata, and export notes linked to an owner-scoped content project.</p></div><div className="grid gap-3 md:grid-cols-2"><div className="space-y-1"><Label>Content project</Label><Select value={projectId} onValueChange={setProjectId}><SelectTrigger><SelectValue placeholder="Select project" /></SelectTrigger><SelectContent>{projects.data?.map(project => <SelectItem key={project.id} value={String(project.id)}>{project.title}</SelectItem>)}</SelectContent></Select></div><div className="space-y-1"><Label>Lifecycle stage</Label><Select value={stage} onValueChange={value => setStageValue(value as typeof stage)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{stages.map(item => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div></div>{projectId ? <><div className="space-y-1"><Label>Outline</Label><Textarea value={outline} onChange={event => setOutline(event.target.value)} placeholder="Argument structure, sections, and source-supported claims." /></div><div className="space-y-1"><Label>Script</Label><Textarea value={script} onChange={event => setScript(event.target.value)} placeholder="Narration or article draft." /></div><div className="space-y-1"><Label>Storyboard</Label><Textarea value={storyboard} onChange={event => setStoryboard(event.target.value)} placeholder="Scene sequence, visual references, and on-screen treatment." /></div><div className="grid gap-3 md:grid-cols-2"><div className="space-y-1"><Label>Metadata tags</Label><Input value={tags} onChange={event => setTags(event.target.value)} placeholder="research, explainer, vertical-video" /></div><div className="space-y-1"><Label>Export notes</Label><Input value={exportNotes} onChange={event => setExportNotes(event.target.value)} placeholder="Publication or delivery notes" /></div></div><div className="flex justify-end gap-2"><Button variant="outline" disabled={busy} onClick={() => updateStage.mutate({ contentProjectId: Number(projectId), stage })}>Set stage</Button><Button disabled={busy} onClick={() => updateArtifacts.mutate({ contentProjectId: Number(projectId), outline: outline || undefined, script: script || undefined, storyboard: storyboard || undefined, exportNotes: exportNotes || undefined, tags: tags.split(",").map(tag => tag.trim()).filter(Boolean) })}>Save artifacts</Button></div></> : <div className="rounded-xl border border-dashed border-slate-200 p-5 text-center text-sm text-slate-500"><FileText className="mx-auto mb-2 size-5 text-slate-300" />Create a content project before recording artifacts.</div>}</CardContent></Card>;
}
