import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { CalendarPlus } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const modes = ["once", "hourly", "daily", "weekly", "monthly", "cron", "event"] as const;
export function ScheduleDefinitionPanel() {
  const workflows = trpc.workflows.list.useQuery(); const [workflowId, setWorkflowId] = useState(""); const [name, setName] = useState(""); const [mode, setMode] = useState<(typeof modes)[number]>("once"); const [timezone, setTimezone] = useState("UTC"); const [runAt, setRunAt] = useState(""); const [day, setDay] = useState("1"); const [eventName, setEventName] = useState(""); const [cron, setCron] = useState("0 0 9 * * *");
  const create = trpc.schedules.create.useMutation({ onSuccess: () => { toast.success("Schedule definition saved as paused until production activation."); setName(""); }, onError: error => toast.error(error.message) });
  const config = mode === "once" ? { runAt } : mode === "weekly" ? { dayOfWeek: Number(day) } : mode === "monthly" ? { dayOfMonth: Number(day) } : mode === "event" ? { eventName } : undefined;
  const validConfig = mode === "once" ? !!runAt : mode === "weekly" ? Number(day) >= 0 && Number(day) <= 6 : mode === "monthly" ? Number(day) >= 1 && Number(day) <= 31 : mode === "event" ? eventName.trim().length >= 2 : true;
  return <Card className="blueprint-card border-0"><CardContent className="space-y-4 p-5"><div><p className="eyebrow">RECURRENCE-AWARE DEFINITION</p><p className="mt-2 text-sm leading-6 text-slate-600">Every schedule is saved paused. Its specific recurrence fields are retained for a future signed, idempotent execution adapter.</p></div><div className="grid gap-3 md:grid-cols-2"><div className="space-y-1"><Label>Workflow</Label><Select value={workflowId} onValueChange={setWorkflowId}><SelectTrigger><SelectValue placeholder="Select workflow" /></SelectTrigger><SelectContent>{workflows.data?.map(workflow => <SelectItem key={workflow.id} value={String(workflow.id)}>{workflow.name}</SelectItem>)}</SelectContent></Select></div><div className="space-y-1"><Label>Schedule name</Label><Input value={name} onChange={event => setName(event.target.value)} placeholder="Research digest" /></div><div className="space-y-1"><Label>Recurrence</Label><Select value={mode} onValueChange={value => setMode(value as typeof mode)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{modes.map(item => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div><div className="space-y-1"><Label>Timezone</Label><Input value={timezone} onChange={event => setTimezone(event.target.value)} /></div>{mode === "once" && <div className="space-y-1 md:col-span-2"><Label>Run at (ISO timestamp)</Label><Input value={runAt} onChange={event => setRunAt(event.target.value)} placeholder="2026-08-20T09:00:00Z" /></div>}{mode === "weekly" && <div className="space-y-1"><Label>Day of week (0–6)</Label><Input value={day} onChange={event => setDay(event.target.value)} inputMode="numeric" /></div>}{mode === "monthly" && <div className="space-y-1"><Label>Day of month (1–31)</Label><Input value={day} onChange={event => setDay(event.target.value)} inputMode="numeric" /></div>}{mode === "event" && <div className="space-y-1 md:col-span-2"><Label>Event name</Label><Input value={eventName} onChange={event => setEventName(event.target.value)} placeholder="content.project.approved" /></div>}{mode === "cron" && <div className="space-y-1 md:col-span-2"><Label>Six-field cron expression</Label><Input value={cron} onChange={event => setCron(event.target.value)} /></div>}</div><Button disabled={create.isPending || !workflowId || name.trim().length < 2 || !validConfig} onClick={() => create.mutate({ workflowId: Number(workflowId), name, recurrenceType: mode, timezone, cronExpression: mode === "cron" ? cron : undefined, recurrenceConfig: config })}><CalendarPlus className="mr-2 size-4" />Save paused schedule</Button></CardContent></Card>;
}
