#!/usr/bin/env bash
set -u
ROOT="/home/ubuntu/github-workspace"
REPOS="$ROOT/repos"
CP="$ROOT/checkpoints"
LOGDIR="$CP/daily_logs"
mkdir -p "$LOGDIR"
STAMP=$(date +%Y%m%d_%H%M%S)
SUMMARY="$CP/daily_latest.tsv"
RUNLOG="$LOGDIR/$STAMP.log"
exec > >(tee -a "$RUNLOG") 2>&1
printf 'step\treturn_code\tlog\n' > "$SUMMARY"
overall_rc=0
run_step() {
  local name="$1"; shift
  local log="$CP/${name}_${STAMP}.log"
  set +e
  "$@" >"$log" 2>&1
  local rc=$?
  set -e
  printf '%s\t%s\t%s\n' "$name" "$rc" "$log" >> "$SUMMARY"
  cat "$log"
  [ "$rc" -eq 0 ] || overall_rc=1
  return 0
}
run_step static-triage "$CP/run_repo_checks_cycle.sh" "$CP/repo_checks_daily.tsv"
run_step project-checks "$CP/run_project_checks_cycle2.sh" "$CP/project_checks_daily.tsv"
run_step exact-tests "$CP/run_exact_tests.sh" "$REPOS" "$CP/exact_tests_daily.tsv" "$CP/exact_test_logs_daily"
run_step python-tests bash -lc "cd '$REPOS/daily-research-reels-automation' && pytest -q; a=\$?; cd '$REPOS/pharma-outreach-automation' && pytest -q; b=\$?; exit \$((a||b))"
# Remove only bytecode caches generated by the maintenance test run.
find "$REPOS" -type d -name __pycache__ -prune -exec rm -rf {} +
set +e
git_rc=0
for dir in "$REPOS"/*; do
  [ -d "$dir/.git" ] || continue
  if [ -n "$(git -C "$dir" status --porcelain)" ]; then
    printf 'DIRTY %s\n' "${dir##*/}"
    git -C "$dir" status --short
    git_rc=1
  fi
done
set -e
printf 'git-status\t%s\t%s\n' "$git_rc" "$RUNLOG" >> "$SUMMARY"
[ "$git_rc" -eq 0 ] || overall_rc=1
printf 'daily_summary=%s\n' "$SUMMARY"
printf 'daily_log=%s\n' "$RUNLOG"
exit "$overall_rc"
