import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { Activity, ArrowRight, Bot, CalendarClock, CircleAlert, GitBranch, Play, RadioTower, Sparkles, Workflow } from "lucide-react";
import { useLocation } from "wouter";

const metricConfig = [
  { key: "activeAgents", label: "Active agents", icon: Bot, accent: "bg-cyan-100 text-cyan-900", path: "/agents" },
  { key: "runningWorkflows", label: "Running workflows", icon: Workflow, accent: "bg-soft-pink text-rose-900", path: "/workflows" },
  { key: "activeSchedules", label: "Scheduled jobs", icon: CalendarClock, accent: "bg-amber-100 text-amber-900", path: "/schedules" },
  { key: "projects", label: "Tracked projects", icon: GitBranch, accent: "bg-violet-100 text-violet-900", path: "/projects" },
] as const;

function formatDate(value: string | Date | null) { return value ? new Date(value).toLocaleString(undefined, { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }) : "Not run"; }
function runTone(status: string) { return status === "succeeded" ? "bg-emerald-50 text-emerald-700 border-emerald-200" : status === "failed" ? "bg-rose-50 text-rose-700 border-rose-200" : status === "running" ? "bg-cyan-50 text-cyan-700 border-cyan-200" : "bg-slate-50 text-slate-600 border-slate-200"; }

export default function DashboardPage() {
  const [, setLocation] = useLocation();
  const snapshot = trpc.commandCenter.dashboard.useQuery();
  const integrations = trpc.commandCenter.integrationHealth.useQuery();
  if (snapshot.isLoading) return <div className="space-y-6"><Skeleton className="h-44 w-full rounded-2xl" /><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{Array.from({ length: 4 }).map((_, i) => <Skeleton key={i} className="h-36 rounded-2xl" />)}</div></div>;
  if (snapshot.isError) return <div className="mx-auto max-w-3xl"><Card className="border-rose-200 bg-rose-50"><CardContent className="p-6"><div className="flex items-start gap-3"><CircleAlert className="mt-0.5 size-5 text-rose-700" /><div><h1 className="font-semibold text-rose-950">Dashboard data could not be loaded</h1><p className="mt-1 text-sm leading-6 text-rose-800">The command-center snapshot is temporarily unavailable. No agent, workflow, deployment, or provider action has been invoked.</p><Button className="mt-4" variant="outline" onClick={() => snapshot.refetch()}>Retry dashboard</Button></div></div></CardContent></Card></div>;
  const metrics = snapshot.data?.metrics;
  return <div className="mx-auto max-w-[1500px] space-y-6">
    <section className="blueprint-card relative overflow-hidden px-6 py-7 sm:px-8">
      <div className="absolute -right-16 -top-16 size-56 rounded-full border border-cyan-200/80" /><div className="absolute right-12 top-10 size-32 rotate-45 border border-rose-200/80" />
      <div className="relative max-w-3xl"><p className="eyebrow">AUTONOMOUS OPERATIONS / CONTROL PLANE</p><h1 className="mt-3 max-w-2xl text-4xl font-black leading-[0.96] tracking-[-0.06em] text-slate-950 sm:text-5xl">Coordinate systems. <span className="text-cyan-700">Verify every action.</span></h1><p className="mt-4 max-w-xl text-sm leading-6 text-slate-600">A single operational surface for AI agents, workflows, content systems, integrations, and deployment signals. Connection states below are live—not assumed.</p><div className="mt-6 flex flex-wrap gap-3"><Button onClick={() => setLocation("/chat")} className="bg-slate-950 text-white hover:bg-slate-800"><Sparkles className="mr-2 size-4" />Open AI command line</Button><Button variant="outline" onClick={() => setLocation("/integrations")}><RadioTower className="mr-2 size-4" />Review integrations</Button></div></div>
      <div className="formula-label absolute bottom-5 right-6 hidden text-right lg:block">Σ(executions) → observed state<br />policy(action) = verify(permission)</div>
    </section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metricConfig.map(item => { const Icon = item.icon; const value = metrics?.[item.key] ?? 0; return <button key={item.key} onClick={() => setLocation(item.path)} className="blueprint-card group p-5 text-left transition-transform hover:-translate-y-0.5"><div className="flex items-start justify-between"><span className={`flex size-9 items-center justify-center rounded-xl ${item.accent}`}><Icon className="size-4" /></span><ArrowRight className="size-4 text-slate-300 transition-transform group-hover:translate-x-0.5 group-hover:text-slate-600" /></div><p className="mt-5 text-3xl font-black tracking-[-0.05em] text-slate-950">{value}</p><p className="mt-1 font-mono text-[10px] uppercase tracking-[0.12em] text-slate-500">{item.label}</p></button>; })}</section>
    <section className="grid gap-6 xl:grid-cols-[1.45fr_0.8fr]">
      <Card className="blueprint-card border-0"><CardContent className="p-0"><div className="flex items-center justify-between border-b border-slate-200/80 px-5 py-4"><div><p className="eyebrow">EXECUTION TRACE</p><h3 className="mt-1 text-base font-bold tracking-[-0.025em]">Recent workflow activity</h3></div><Button variant="ghost" size="sm" onClick={() => setLocation("/logs")}>View logs <ArrowRight className="ml-1 size-3.5" /></Button></div><div className="divide-y divide-slate-100">{snapshot.data?.recentRuns.length ? snapshot.data.recentRuns.map(run => <div key={run.id} className="flex items-center gap-3 px-5 py-4"><div className="flex size-8 shrink-0 items-center justify-center rounded-full bg-slate-100"><Play className="size-3 text-slate-600" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">Workflow run #{run.id}</p><p className="font-mono text-[10px] text-slate-500">{run.triggerSource} · {formatDate(run.createdAt)}</p></div><Badge variant="outline" className={`font-mono text-[10px] ${runTone(run.status)}`}>{run.status.replace("_", " ")}</Badge></div>) : <div className="p-8 text-center"><Activity className="mx-auto size-5 text-slate-300" /><p className="mt-3 text-sm font-medium">No execution traces yet</p><p className="mt-1 text-xs text-slate-500">Create a workflow to establish an auditable run history.</p><Button size="sm" variant="outline" className="mt-4" onClick={() => setLocation("/workflows")}>Open workflow builder</Button></div>}</div></CardContent></Card>
      <Card className="blueprint-card border-0"><CardContent className="p-0"><div className="border-b border-slate-200/80 px-5 py-4"><p className="eyebrow">INTEGRATION HEALTH</p><h3 className="mt-1 text-base font-bold tracking-[-0.025em]">Verified connection map</h3></div><div className="divide-y divide-slate-100">{integrations.isLoading ? Array.from({ length: 4 }).map((_, i) => <div key={i} className="p-4"><Skeleton className="h-4 w-28" /></div>) : integrations.isError ? <div className="p-5 text-sm text-rose-800">Integration health could not be loaded. <Button variant="link" className="h-auto p-0 text-rose-800" onClick={() => integrations.refetch()}>Retry</Button></div> : integrations.data?.length ? integrations.data.slice(0, 5).map(item => <div key={item.service} className="flex gap-3 px-5 py-3.5"><div className={`mt-1.5 size-2 shrink-0 rounded-full ${item.connectionStatus === "connected" || item.connectionStatus === "available" ? "bg-emerald-400" : item.connectionStatus === "error" ? "bg-rose-400" : "bg-amber-400"}`} /><div className="min-w-0"><div className="flex items-center gap-2"><p className="text-sm font-medium">{item.displayName}</p><span className="font-mono text-[9px] uppercase text-slate-400">{item.connectionStatus.replace("_", " ")}</span></div><p className="mt-0.5 line-clamp-2 text-[11px] leading-4 text-slate-500">{item.detail}</p></div></div>) : <div className="p-5 text-sm text-slate-500">No integration health records are available yet.</div>}</div><div className="border-t border-slate-100 p-3"><Button variant="ghost" size="sm" className="w-full text-xs" onClick={() => setLocation("/integrations")}><CircleAlert className="mr-2 size-3.5" />Review all connection requirements</Button></div></CardContent></Card>
    </section>
    <section className="blueprint-card grid gap-4 p-5 md:grid-cols-[1fr_auto] md:items-center"><div><p className="eyebrow">DEPLOYMENT TARGETS</p><h3 className="mt-1 text-base font-bold tracking-[-0.025em]">Four provider targets are registered for health monitoring.</h3><p className="mt-1 text-sm text-slate-500">GitHub, Vercel, Cloudflare, and Google Cloud remain visibly not connected until application credentials and health checks are configured.</p></div><div className="flex flex-wrap gap-2">{snapshot.data?.deployments.map(item => <Badge key={item.status} variant="outline" className="font-mono text-[10px]">{item.status}: {item.count}</Badge>)}</div></section>
    <section className="blueprint-card p-5"><div className="flex items-center justify-between"><div><p className="eyebrow">AGENT POLICY ACTIVITY</p><h3 className="mt-1 text-base font-bold tracking-[-0.025em]">Recent agent configuration events</h3></div><Button variant="ghost" size="sm" onClick={() => setLocation("/agents")}>Open agents <ArrowRight className="ml-1 size-3.5" /></Button></div>{snapshot.data?.recentAgentActivity.length ? <div className="mt-4 grid gap-3 md:grid-cols-2">{snapshot.data.recentAgentActivity.map(event => <div key={event.id} className="rounded-xl border border-slate-100 bg-white/70 p-3"><p className="text-sm font-medium">{event.action}</p><p className="mt-1 text-xs text-slate-500">{event.detail || "Agent policy event"}</p></div>)}</div> : <p className="mt-4 text-sm text-slate-500">No agent policy events yet. Creating or updating an agent will appear here.</p>}</section>
  </div>;
}
