import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { Upload } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

export function MediaUploadPage() {
  const utils = trpc.useUtils();
  const assets = trpc.media.list.useQuery();
  const projects = trpc.content.list.useQuery();
  const [file, setFile] = useState<File | null>(null);
  const [contentProjectId, setContentProjectId] = useState("");
  useEffect(() => { if (!contentProjectId && projects.data?.[0]) setContentProjectId(String(projects.data[0].id)); }, [contentProjectId, projects.data]);
  const upload = trpc.media.upload.useMutation({ onSuccess: async () => { await utils.media.list.invalidate(); setFile(null); toast.success("Media asset stored in managed project context"); }, onError: error => toast.error(error.message) });
  const sendFile = async () => { if (!file) return; if (file.size > 5 * 1024 * 1024) return toast.error("Choose a file smaller than 5 MB"); try { const dataBase64 = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onerror = () => reject(new Error("Could not read the selected file")); reader.onload = () => resolve(String(reader.result).split(",")[1] || ""); reader.readAsDataURL(file); }); const kind = file.type.startsWith("image/") ? "image" : file.type.startsWith("audio/") ? "audio" : file.type.startsWith("video/") ? "video" : file.type === "application/pdf" ? "document" : "other"; upload.mutate({ name: file.name, kind, mimeType: file.type || "application/octet-stream", dataBase64, contentProjectId: contentProjectId ? Number(contentProjectId) : undefined }); } catch (error) { toast.error(error instanceof Error ? error.message : "The selected file could not be read"); } };
  return <div className="mx-auto max-w-[1250px] space-y-6"><section className="blueprint-card p-7 sm:p-9"><p className="eyebrow">IMAGE / AUDIO / VIDEO / DOCUMENT</p><h1 className="mt-2 text-4xl font-black tracking-[-0.055em] text-slate-950">Media Library</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600">Store compact media in managed storage and associate it with the owner-scoped content project that will use it. The association supports provenance checks; it does not trigger rendering or delivery.</p></section><Card className="blueprint-card border-0"><CardContent className="grid gap-4 p-6 md:grid-cols-[1fr_1fr_auto]"><div className="space-y-2"><Label>Content project <span className="text-slate-400">optional</span></Label><Select value={contentProjectId} onValueChange={setContentProjectId}><SelectTrigger><SelectValue placeholder="Unattached managed asset" /></SelectTrigger><SelectContent>{projects.data?.map(project => <SelectItem key={project.id} value={String(project.id)}>{project.title}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Asset file <span className="text-slate-400">maximum 5 MB</span></Label><Input type="file" accept="image/*,audio/*,video/*,application/pdf" onChange={event => setFile(event.target.files?.[0] ?? null)} /></div><div className="flex items-end"><Button className="w-full" disabled={!file || upload.isPending} onClick={sendFile}><Upload className="mr-2 size-4" />{upload.isPending ? "Storing…" : "Store asset"}</Button></div></CardContent></Card><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{assets.isLoading ? Array.from({ length: 3 }).map((_, index) => <Card key={index} className="h-48 animate-pulse border-0 bg-slate-100" />) : assets.isError ? <div className="blueprint-card col-span-full p-6 text-sm text-rose-800">Managed media could not be loaded. Please retry after confirming the session.</div> : assets.data?.length ? assets.data.map(asset => <Card key={asset.id} className="blueprint-card overflow-hidden border-0">{asset.kind === "image" || asset.kind === "thumbnail" ? <img src={asset.storageUrl} alt={asset.name} className="aspect-[16/10] w-full object-cover" /> : <div className="flex aspect-[16/10] items-center justify-center bg-slate-50"><Upload className="size-8 text-slate-300" /></div>}<CardContent className="p-4"><p className="truncate text-sm font-semibold">{asset.name}</p><p className="mt-1 font-mono text-[10px] uppercase text-slate-400">{asset.kind} · {asset.mimeType || "unknown"}</p><p className="mt-2 text-xs text-slate-500">{asset.contentProjectId ? `Project #${asset.contentProjectId}` : "Unattached managed asset"}</p><a href={asset.storageUrl} target="_blank" rel="noreferrer" className="mt-3 inline-block text-xs text-cyan-700 underline underline-offset-4">Open asset</a></CardContent></Card>) : <div className="blueprint-card col-span-full py-16 text-center text-sm text-slate-500">No stored media assets yet.</div>}</section></div>;
}
