import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ArrowUpRight, Boxes, CloudCog, FileChartColumnIncreasing, Github, Image, ListChecks, RadioTower, Video, Waypoints } from "lucide-react";
import { useLocation } from "wouter";

const moduleInfo: Record<string, { title: string; eyebrow: string; description: string; icon: typeof Waypoints; capability: string; }> = {
  github: { title: "GitHub Intelligence", eyebrow: "AUTHORIZED SOURCE CONTROL", description: "Browse repositories, issues, pull requests, commit history, and code-review workflows after an application-level GitHub connection is authorized.", icon: Github, capability: "Repository credentials are not inherited from a browser session." },
  content: { title: "Content Studio", eyebrow: "RESEARCH → SCRIPT → STORYBOARD", description: "Track research sources, evidence labels, scripts, storyboards, metadata, assets, and export-ready content projects in one auditable pipeline.", icon: FileChartColumnIncreasing, capability: "Create content projects in the next implementation phase." },
  video: { title: "Video Studio", eyebrow: "VERTICAL VIDEO PIPELINE", description: "Organize 9:16 short-form video jobs, edit plans, captions, voice-over, and export review. Hardware-intensive rendering stays explicitly queued until an authorized render service exists.", icon: Video, capability: "Video rendering is not simulated in the managed app runtime." },
  images: { title: "Image Studio", eyebrow: "VISUAL ASSET GENERATION", description: "Generate storyboard frames, thumbnails, and illustrative visuals with server-side generation and managed asset storage.", icon: Image, capability: "Generation actions are enabled from a content job, not fabricated here." },
  research: { title: "Research Studio", eyebrow: "SOURCE-GROUNDED WORK", description: "Build research dossiers with source URLs, credibility signals, script linkage, and claim classification for established findings, emerging evidence, opinions, and hypotheses.", icon: FileChartColumnIncreasing, capability: "Research records are scoped to content projects." },
  deployments: { title: "Deployment Control", eyebrow: "TARGET HEALTH / ROLLBACK READINESS", description: "Maintain a clear inventory of GitHub, Vercel, Cloudflare, and Google Cloud targets. Each target remains visibly disconnected until a credential-backed health check succeeds.", icon: CloudCog, capability: "No deployment is executed from a placeholder control." },
  integrations: { title: "Integration Health", eyebrow: "AUTHORIZED CONNECTION REGISTRY", description: "Inspect each provider’s real availability, authorization state, connection boundary, and required next action before building a workflow around it.", icon: RadioTower, capability: "A browser or agent-session login is not treated as an application credential." },
  logs: { title: "Execution Logs", eyebrow: "SEARCHABLE AUDIT TRAIL", description: "Review workflow traces, retry states, policy outcomes, model calls, errors, and system events as an accountable operating record.", icon: ListChecks, capability: "Execution records appear as workflows and agents run." },
  settings: { title: "System Settings", eyebrow: "POLICY / COST / PERMISSIONS", description: "Centralize approval policy, retention, system defaults, cost awareness, and connection configuration without storing raw provider credentials in application tables.", icon: Boxes, capability: "Security-sensitive settings require explicit integration configuration." },
};

const deploymentDetails = {
  github: { label: "Source-control target", requirement: "The authorized application token is used only for scoped repository health and read-only repository data.", disconnected: "GitHub target is disconnected until an authorized repository credential and mapping are available." },
  vercel: { label: "Application deployment target", requirement: "A Vercel API credential and project mapping are required before release health can be verified.", disconnected: "Vercel is unavailable because no credential-backed project mapping is configured." },
  cloudflare: { label: "Edge and DNS target", requirement: "A Cloudflare API credential and zone or Worker mapping are required before edge health can be verified.", disconnected: "Cloudflare is unavailable because no credential-backed zone or Worker mapping is configured." },
  google_cloud: { label: "Cloud runtime target", requirement: "A scoped Google Cloud service credential and deployment target are required before runtime health can be verified.", disconnected: "Google Cloud is unavailable because no credential-backed deployment target is configured." },
  other: { label: "External target", requirement: "A scoped provider credential and target mapping are required before health can be verified.", disconnected: "This deployment target is not connected to a verified provider credential." },
} as const;

export default function ModulePage({ module }: { module: string }) {
  const [, setLocation] = useLocation();
  const item = moduleInfo[module] ?? moduleInfo.settings;
  const Icon = item.icon;
  const integrations = trpc.commandCenter.integrationHealth.useQuery(undefined, { enabled: module === "deployments" || module === "github" || module === "settings" || module === "integrations" });
  const deploymentTargets = trpc.commandCenter.deploymentTargets.useQuery(undefined, { enabled: module === "deployments" });
  const githubRepos = trpc.github.repos.useQuery(undefined, { enabled: module === "github" });
  return <div className="mx-auto max-w-[1250px] space-y-6">
    <section className="blueprint-card relative overflow-hidden p-7 sm:p-9"><div className="absolute right-10 top-8 hidden size-36 rotate-12 rounded-[2rem] border border-cyan-200 bg-cyan-50/40 lg:block" /><div className="relative max-w-2xl"><span className="flex size-11 items-center justify-center rounded-2xl bg-soft-pink text-slate-900"><Icon className="size-5" /></span><p className="eyebrow mt-6">{item.eyebrow}</p><h1 className="mt-2 text-4xl font-black tracking-[-0.055em] text-slate-950">{item.title}</h1><p className="mt-4 max-w-xl text-sm leading-6 text-slate-600">{item.description}</p></div></section>
    <Card className="blueprint-card border-0"><CardContent className="p-6"><div className="flex items-start gap-3"><div className="mt-0.5 rounded-xl bg-amber-100 p-2 text-amber-800"><AlertTriangle className="size-4" /></div><div><p className="font-semibold">Capability boundary</p><p className="mt-1 max-w-3xl text-sm leading-6 text-slate-600">{item.capability}</p></div></div></CardContent></Card>
    {(module === "deployments" || module === "github" || module === "settings" || module === "integrations") && <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{integrations.isLoading ? Array.from({ length: 3 }).map((_, index) => <Card key={index} className="h-40 animate-pulse border-0 bg-slate-100" />) : integrations.data?.filter(integration => module === "github" ? integration.service === "github" : module === "deployments" ? integration.category === "deployment" : true).map(integration => <Card key={integration.service} className="blueprint-card border-0"><CardContent className="p-5"><div className="flex items-center justify-between gap-3"><p className="font-semibold">{integration.displayName}</p><Badge variant="outline" className="font-mono text-[10px]">{integration.connectionStatus.replaceAll("_", " ")}</Badge></div><p className="mt-3 text-xs leading-5 text-slate-500">{integration.detail}</p><p className="mt-4 border-t border-slate-100 pt-3 font-mono text-[10px] text-slate-400">{integration.verificationState === "provider_verified" && integration.lastHealthCheckAt ? `Provider verified ${new Date(integration.lastHealthCheckAt).toLocaleString()}` : "Registry default · provider verification pending"}</p>{integration.verificationState === "registry_default" && <p className="mt-2 text-xs text-amber-800">This registry entry is not evidence of a live provider connection.</p>}{["blocked", "unavailable", "disconnected", "action_required"].includes(integration.connectionStatus) && <p className="mt-2 text-xs text-amber-800">Provider actions remain unavailable until an authorized application credential is configured.</p>}</CardContent></Card>)}</section>}
    {module === "deployments" && <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{deploymentTargets.isLoading ? Array.from({ length: 4 }).map((_, index) => <Card key={index} className="h-56 animate-pulse border-0 bg-slate-100" />) : deploymentTargets.isError ? <div className="blueprint-card col-span-full p-6 text-sm text-rose-800">Deployment targets could not be loaded. Refresh health after confirming the authenticated session.</div> : deploymentTargets.data?.length ? deploymentTargets.data.map(target => { const detail = deploymentDetails[target.provider as keyof typeof deploymentDetails] ?? deploymentDetails.other; const metadata = (target.metadata ?? {}) as Record<string, unknown>; const verifiedDetail = typeof metadata.detail === "string" ? metadata.detail : null; const isConnected = target.status === "healthy" || target.status === "degraded"; return <Card key={target.id} className="blueprint-card border-0"><CardContent className="p-5"><p className="font-mono text-[10px] uppercase tracking-[0.12em] text-cyan-800">{target.provider.replace("_", " ")}</p><p className="mt-2 font-semibold">{target.name}</p><p className="mt-1 text-xs text-slate-500">{detail.label}</p><Badge variant="outline" className={`mt-3 font-mono text-[10px] ${target.status === "healthy" ? "border-emerald-300 bg-emerald-50 text-emerald-800" : target.status === "degraded" ? "border-amber-300 bg-amber-50 text-amber-800" : "border-slate-200 text-slate-600"}`}>{target.status.replace("_", " ")}</Badge><p className="mt-3 text-xs leading-5 text-slate-600">{isConnected ? verifiedDetail || detail.requirement : detail.disconnected}</p>{target.endpointUrl && <a className="mt-3 block truncate text-xs text-cyan-700 underline underline-offset-4" href={target.endpointUrl} target="_blank" rel="noreferrer">Open mapped endpoint</a>}<p className="mt-3 border-t border-slate-100 pt-3 text-[11px] text-slate-400">{target.lastHealthCheckAt ? `Last checked ${new Date(target.lastHealthCheckAt).toLocaleString()}` : "No credential-backed health check yet."}</p></CardContent></Card>; }) : <div className="blueprint-card col-span-full py-14 text-center text-sm text-slate-500">No owner-scoped deployment targets are registered.</div>}</section>}
    {module === "github" && <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{githubRepos.isLoading ? <div className="blueprint-card col-span-full py-14 text-center text-sm text-slate-500">Loading authorized repository inventory…</div> : githubRepos.data?.length ? githubRepos.data.map(repo => <Card key={repo.fullName} className="blueprint-card border-0"><CardContent className="p-5"><div className="flex items-center justify-between"><p className="font-semibold">{repo.fullName}</p><Badge variant="outline" className="font-mono text-[10px]">{repo.private ? "private" : "public"}</Badge></div><p className="mt-3 line-clamp-2 min-h-10 text-xs text-slate-500">{repo.description || "No repository description."}</p><p className="mt-3 font-mono text-[10px] uppercase text-cyan-800">{repo.defaultBranch}</p><a href={repo.url} target="_blank" rel="noreferrer" className="mt-4 inline-block text-xs text-cyan-700 underline underline-offset-4">Open repository</a></CardContent></Card>) : <div className="blueprint-card col-span-full py-14 text-center text-sm text-slate-500">No repositories are visible to the configured application credential.</div>}</section>}
    <div className="flex flex-wrap justify-end gap-2">{(module === "deployments" || module === "integrations") && <Button variant="outline" disabled={integrations.isFetching || deploymentTargets.isFetching} onClick={() => Promise.all([integrations.refetch(), module === "deployments" ? deploymentTargets.refetch() : Promise.resolve()])}>{integrations.isFetching || deploymentTargets.isFetching ? "Refreshing health…" : "Refresh health"}</Button>}<Button variant="outline" onClick={() => setLocation("/integrations")}>Open integration health <ArrowUpRight className="ml-2 size-4" /></Button></div>
  </div>;
}
