import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { AgentDispatchControl, AgentDispatchHistory } from "@/components/ApprovalResolutionControls";
import { trpc } from "@/lib/trpc";
import { Bot, Boxes, ChevronRight, FolderGit2, Pencil, Plus, ShieldCheck, TerminalSquare, Trash2 } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

function SectionIntro({ eyebrow, title, description, icon: Icon }: { eyebrow: string; title: string; description: string; icon: typeof Boxes }) {
  return <section className="blueprint-card relative overflow-hidden p-7 sm:p-9"><div className="absolute right-8 top-8 hidden size-28 rounded-full border border-cyan-200 lg:block" /><div className="relative max-w-2xl"><span className="flex size-11 items-center justify-center rounded-2xl bg-cyan-100 text-cyan-900"><Icon className="size-5" /></span><p className="eyebrow mt-6">{eyebrow}</p><h1 className="mt-2 text-4xl font-black tracking-[-0.055em] text-slate-950">{title}</h1><p className="mt-4 text-sm leading-6 text-slate-600">{description}</p></div></section>;
}

export function ProjectsPage() {
  const utils = trpc.useUtils();
  const projects = trpc.projects.list.useQuery();
  const [open, setOpen] = useState(false);
  const [editingProjectId, setEditingProjectId] = useState<number | null>(null);
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [repositoryUrl, setRepositoryUrl] = useState("");
  const create = trpc.projects.create.useMutation({ onSuccess: async () => { await utils.projects.list.invalidate(); await utils.commandCenter.dashboard.invalidate(); setOpen(false); setName(""); setDescription(""); setRepositoryUrl(""); toast.success("Project created"); }, onError: error => toast.error(error.message) });
  const update = trpc.projects.update.useMutation({ onSuccess: async () => { await utils.projects.list.invalidate(); setOpen(false); setEditingProjectId(null); toast.success("Project updated"); }, onError: error => toast.error(error.message) });
  const remove = trpc.projects.remove.useMutation({ onSuccess: async () => { await Promise.all([utils.projects.list.invalidate(), utils.commandCenter.dashboard.invalidate()]); toast.success("Project deleted"); }, onError: error => toast.error(error.message) });
  return <div className="mx-auto max-w-[1250px] space-y-6"><SectionIntro eyebrow="OWNED WORKSPACES / REPOSITORY CONTEXT" title="Projects" description="Create a governed workspace for agents, workflows, content operations, and authorized repository metadata. Each project is isolated to your account." icon={FolderGit2} />
    <div className="flex justify-end gap-2"><Button variant="outline" asChild><a href="/projects/activity">Activity history</a></Button><Button onClick={() => { setEditingProjectId(null); setName(""); setDescription(""); setRepositoryUrl(""); setOpen(true); }}><Plus className="mr-2 size-4" />New project</Button></div>
    {open && <Card className="blueprint-card border-0"><CardContent className="grid gap-4 p-6 md:grid-cols-2"><div className="space-y-2"><Label htmlFor="project-name">Project name</Label><Input id="project-name" value={name} onChange={e => setName(e.target.value)} placeholder="Release intelligence" /></div><div className="space-y-2"><Label htmlFor="project-repo">Repository URL <span className="text-muted-foreground">optional</span></Label><Input id="project-repo" value={repositoryUrl} onChange={e => setRepositoryUrl(e.target.value)} placeholder="https://github.com/owner/repo" /></div><div className="space-y-2 md:col-span-2"><Label htmlFor="project-description">Operating brief</Label><Textarea id="project-description" value={description} onChange={e => setDescription(e.target.value)} placeholder="What should this command center coordinate?" /></div><div className="flex justify-end gap-2 md:col-span-2"><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button disabled={create.isPending || update.isPending || name.trim().length < 2} onClick={() => editingProjectId ? update.mutate({ id: editingProjectId, name, description: description || undefined, repositoryUrl: repositoryUrl || undefined, status: "active" }) : create.mutate({ name, description: description || undefined, repositoryUrl: repositoryUrl || undefined })}>{editingProjectId ? "Save project" : "Create workspace"}</Button></div></CardContent></Card>}
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{projects.isLoading ? Array.from({ length: 3 }).map((_, index) => <Card key={index} className="h-44 animate-pulse bg-slate-100" />) : projects.data?.length ? projects.data.map(project => <Card key={project.id} className="blueprint-card border-0"><CardContent className="p-5"><div className="flex items-start justify-between"><span className="flex size-9 items-center justify-center rounded-xl bg-soft-pink"><FolderGit2 className="size-4" /></span><Badge variant="outline" className="font-mono text-[10px]">{project.status}</Badge></div><h2 className="mt-5 text-lg font-bold tracking-[-0.03em]">{project.name}</h2><p className="mt-2 line-clamp-2 min-h-10 text-sm text-slate-500">{project.description || "No operating brief has been defined."}</p><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4"><span className="font-mono text-[10px] text-slate-400">{project.repositoryUrl ? "REPOSITORY LINKED" : "NO REPOSITORY"}</span><div className="flex gap-1"><Button aria-label={`Edit ${project.name}`} variant="ghost" size="icon" onClick={() => { setEditingProjectId(project.id); setName(project.name); setDescription(project.description || ""); setRepositoryUrl(project.repositoryUrl || ""); setOpen(true); }}><Pencil className="size-3.5" /></Button><Button aria-label={`Delete ${project.name}`} variant="ghost" size="icon" className="text-rose-600" disabled={remove.isPending} onClick={() => remove.mutate({ id: project.id })}><Trash2 className="size-3.5" /></Button></div></div></CardContent></Card>) : <div className="blueprint-card col-span-full py-16 text-center"><FolderGit2 className="mx-auto size-6 text-slate-300" /><p className="mt-3 font-semibold">No projects yet</p><p className="mt-1 text-sm text-slate-500">Create a workspace before attaching agents or workflows.</p></div>}</section>
  </div>;
}

const agentRoles = ["orchestrator", "coding", "research", "automation", "image", "video", "publishing", "qa", "devops", "custom"] as const;
const autonomyOptions = ["manual", "assisted", "autonomous"] as const;
const autonomyCopy = { manual: "Every meaningful action requires confirmation.", assisted: "Routine steps proceed; high-impact actions require review.", autonomous: "Pre-authorized low-risk tasks may continue automatically." };
const formatAutonomy = (level: string) => `${level.slice(0, 1).toUpperCase()}${level.slice(1)}`;

export function AgentsPage() {
  const utils = trpc.useUtils();
  const agents = trpc.agents.list.useQuery();
  const [open, setOpen] = useState(false);
  const [editingAgentId, setEditingAgentId] = useState<number | null>(null);
  const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [role, setRole] = useState<(typeof agentRoles)[number]>("orchestrator"); const [autonomyLevel, setAutonomyLevel] = useState<(typeof autonomyOptions)[number]>("assisted"); const [instructions, setInstructions] = useState(""); const [approvalActions, setApprovalActions] = useState(["publish", "deploy", "delete", "credential_change"]);
  const create = trpc.agents.create.useMutation({ onSuccess: async () => { await utils.agents.list.invalidate(); await utils.commandCenter.dashboard.invalidate(); setOpen(false); setName(""); setDescription(""); setInstructions(""); toast.success("Agent profile created"); }, onError: error => toast.error(error.message) });
  const update = trpc.agents.update.useMutation({ onSuccess: async () => { await Promise.all([utils.agents.list.invalidate(), utils.commandCenter.dashboard.invalidate()]); setOpen(false); setEditingAgentId(null); toast.success("Agent policy updated"); }, onError: error => toast.error(error.message) });
  return <div className="mx-auto max-w-[1250px] space-y-6"><SectionIntro eyebrow="MULTI-AGENT OPERATING SYSTEM" title="Agents" description="Define responsibility, preferred model, instructions, and autonomy policy before any operational work is dispatched." icon={Bot} />{agents.data?.length ? <section className="grid gap-3 lg:grid-cols-2">{agents.data.map(agent => <AgentDispatchControl key={agent.id} agentId={agent.id} agentName={agent.name} />)}</section> : null}<AgentDispatchHistory />
    <div className="grid gap-3 md:grid-cols-3">{autonomyOptions.map(level => <Card key={level} className={`border ${autonomyLevel === level ? "border-cyan-300 bg-cyan-50/70" : "border-slate-200 bg-white/70"}`}><CardContent className="p-4"><p className="font-mono text-[10px] tracking-[0.12em] text-cyan-800">{formatAutonomy(level)}</p><p className="mt-2 text-xs leading-5 text-slate-600">{autonomyCopy[level]}</p></CardContent></Card>)}</div>
    <div className="flex justify-end"><Button onClick={() => { setEditingAgentId(null); setName(""); setDescription(""); setInstructions(""); setRole("orchestrator"); setAutonomyLevel("assisted"); setApprovalActions(["publish", "deploy", "delete", "credential_change"]); setOpen(true); }}><Plus className="mr-2 size-4" />Configure agent</Button></div>
    {open && <div className="grid gap-2 rounded-xl border border-slate-200 bg-slate-50/70 p-4 md:grid-cols-4"><p className="font-mono text-[10px] uppercase tracking-[0.12em] text-slate-500 md:col-span-4">Require review before</p>{["publish", "deploy", "delete", "credential_change"].map(action => <label key={action} className="flex items-center gap-2 rounded-lg bg-white px-3 py-2 text-xs text-slate-700"><Checkbox checked={approvalActions.includes(action)} onCheckedChange={checked => setApprovalActions(current => checked ? (current.includes(action) ? current : current.concat(action)) : current.filter(item => item !== action))} />{action.replace("_", " ")}</label>)}</div>}
    {open && <Card className="blueprint-card border-0"><CardContent className="grid gap-4 p-6 md:grid-cols-2"><div className="space-y-2"><Label htmlFor="agent-name">Agent name</Label><Input id="agent-name" value={name} onChange={e => setName(e.target.value)} placeholder="Release Orchestrator" /></div><div className="space-y-2"><Label>Agent role</Label><Select value={role} onValueChange={value => setRole(value as typeof role)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{agentRoles.map(item => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Autonomy level</Label><Select value={autonomyLevel} onValueChange={value => setAutonomyLevel(value as typeof autonomyLevel)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{autonomyOptions.map(item => <SelectItem key={item} value={item}>{item.charAt(0).toUpperCase() + item.slice(1)}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label htmlFor="agent-description">Purpose</Label><Input id="agent-description" value={description} onChange={e => setDescription(e.target.value)} placeholder="Coordinates approved release workflows" /></div><div className="space-y-2 md:col-span-2"><Label htmlFor="agent-instructions">Operating instructions</Label><Textarea id="agent-instructions" value={instructions} onChange={e => setInstructions(e.target.value)} placeholder="Specify priorities, safety boundaries, and expected output." /></div><div className="rounded-xl border border-amber-200 bg-amber-50/70 p-3 text-xs text-amber-900 md:col-span-2">Publishing, deployment, deletion, and credential changes remain approval-gated at every autonomy level.</div><div className="flex justify-end gap-2 md:col-span-2"><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button disabled={create.isPending || update.isPending || name.trim().length < 2} onClick={() => editingAgentId ? update.mutate({ id: editingAgentId, name, description: description || undefined, role, autonomyLevel, instructions: instructions || undefined, enabled: true, toolPolicy: { approvalRequiredFor: approvalActions } }) : create.mutate({ name, description: description || undefined, role, autonomyLevel, instructions: instructions || undefined, toolPolicy: { approvalRequiredFor: approvalActions } })}>{editingAgentId ? "Save agent policy" : "Create agent policy"}</Button></div></CardContent></Card>}
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{agents.data?.length ? agents.data.map(agent => <Card key={agent.id} className="blueprint-card border-0"><CardContent className="p-5"><div className="flex items-center justify-between"><span className="flex size-9 items-center justify-center rounded-xl bg-cyan-100 text-cyan-900"><Bot className="size-4" /></span><Badge variant="outline" className="font-mono text-[10px]">{agent.autonomyLevel}</Badge></div><h2 className="mt-5 text-lg font-bold tracking-[-0.03em]">{agent.name}</h2><p className="mt-1 font-mono text-[10px] uppercase tracking-[0.12em] text-cyan-800">{agent.role}</p><p className="mt-3 line-clamp-2 min-h-10 text-sm text-slate-500">{agent.description || "No purpose statement configured."}</p><div className="mt-4 flex items-center justify-between gap-2 border-t border-slate-100 pt-4"><span className="flex items-center gap-2 text-xs text-slate-500"><ShieldCheck className="size-3.5 text-emerald-600" />{agent.enabled ? "Policy active" : "Disabled"}</span><Button variant="ghost" size="sm" onClick={() => { const saved = agent.toolPolicy as { approvalRequiredFor?: string[] } | null; setEditingAgentId(agent.id); setName(agent.name); setDescription(agent.description || ""); setRole(agent.role); setAutonomyLevel(agent.autonomyLevel); setInstructions(agent.instructions || ""); setApprovalActions(saved?.approvalRequiredFor?.filter(action => ["publish", "deploy", "delete", "credential_change"].includes(action)) || ["publish", "deploy", "delete", "credential_change"]); setOpen(true); }}>Edit policy</Button></div></CardContent></Card>) : <div className="blueprint-card col-span-full py-16 text-center"><Bot className="mx-auto size-6 text-slate-300" /><p className="mt-3 font-semibold">No agents configured</p><p className="mt-1 text-sm text-slate-500">Start with an orchestrator and define its autonomy boundary.</p></div>}</section>
  </div>;
}

export function LogsPage() {
  const [query, setQuery] = useState("");
  const [outcome, setOutcome] = useState<"all" | "success" | "pending" | "failure" | "denied">("all");
  const logs = trpc.commandCenter.logs.useQuery({ query: query || undefined, outcome: outcome === "all" ? undefined : outcome });
  return <div className="mx-auto max-w-[1250px] space-y-6"><SectionIntro eyebrow="SYSTEM TRACE / POLICY AUDIT" title="Logs" description="Every completed action, error, and policy-relevant state change is recorded as an account-scoped trace." icon={TerminalSquare} /><div className="flex justify-end"><Select value={outcome} onValueChange={value => setOutcome(value as typeof outcome)}><SelectTrigger className="w-44 bg-white"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All outcomes</SelectItem><SelectItem value="success">Success</SelectItem><SelectItem value="pending">Pending</SelectItem><SelectItem value="denied">Denied</SelectItem><SelectItem value="failure">Failure</SelectItem></SelectContent></Select></div>
    <Card className="blueprint-card border-0"><CardContent className="p-0"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 bg-slate-50/70 p-4"><Input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search action, resource, or detail" className="max-w-md bg-white" /><span className="font-mono text-[10px] uppercase tracking-[0.1em] text-slate-400">{logs.data?.length ?? 0} events</span></div><div className="grid grid-cols-[1.2fr_1fr_auto] border-b border-slate-200 bg-slate-50/70 px-5 py-3 font-mono text-[10px] uppercase tracking-[0.12em] text-slate-500"><span>Action</span><span>Resource / time</span><span>Outcome</span></div>{logs.isLoading ? Array.from({ length: 4 }).map((_, index) => <div key={index} className="grid grid-cols-[1.2fr_1fr_auto] gap-3 border-b border-slate-100 px-5 py-4"><div className="h-9 animate-pulse rounded bg-slate-100" /><div className="h-9 animate-pulse rounded bg-slate-100" /><div className="h-6 w-16 animate-pulse rounded bg-slate-100 justify-self-end" /></div>) : logs.data?.length ? logs.data.map(event => <div key={event.id} className="grid grid-cols-[1.2fr_1fr_auto] items-center gap-3 border-b border-slate-100 px-5 py-4 last:border-0"><div><p className="text-sm font-medium">{event.action}</p><p className="mt-1 text-xs text-slate-500">{event.detail || "No additional detail"}</p></div><div><p className="font-mono text-[10px] text-slate-500">{event.resourceType}{event.resourceId ? ` · ${event.resourceId}` : ""}</p><p className="mt-1 text-xs text-slate-400">{new Date(event.createdAt).toLocaleString()}</p></div><Badge variant="outline" className="justify-self-end font-mono text-[10px]">{event.outcome}</Badge></div>) : <div className="p-14 text-center"><TerminalSquare className="mx-auto size-6 text-slate-300" /><p className="mt-3 font-semibold">No matching audit events</p><p className="mt-1 text-sm text-slate-500">Create a project, agent, workflow, or chat to establish an operational trace.</p></div>}</CardContent></Card>
  </div>;
}
