import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { FolderGit2, History } from "lucide-react";
import { useEffect, useState } from "react";

export default function ProjectActivityPage() {
  const projects = trpc.projects.list.useQuery();
  const [projectId, setProjectId] = useState("");
  useEffect(() => { if (!projectId && projects.data?.[0]) setProjectId(String(projects.data[0].id)); }, [projectId, projects.data]);
  const activity = trpc.projects.activity.useQuery({ id: Number(projectId) }, { enabled: Boolean(projectId) });
  if (projects.isError) return <div className="mx-auto max-w-3xl"><Card className="border-rose-200 bg-rose-50"><CardContent className="p-6"><p className="font-semibold text-rose-950">Projects could not be loaded</p><p className="mt-1 text-sm text-rose-800">No project activity has been exposed. Retry after the owner-scoped project list is available.</p><Button className="mt-4" variant="outline" onClick={() => projects.refetch()}>Retry projects</Button></CardContent></Card></div>;
  const activityBody = !projectId ? <div className="p-14 text-center"><FolderGit2 className="mx-auto size-6 text-slate-300" /><p className="mt-3 font-semibold">Select an owned project</p><p className="mt-1 text-sm text-slate-500">Its lifecycle activity will remain restricted to the active account.</p></div> : activity.isLoading ? <div className="p-12 text-center text-sm text-slate-500">Loading project audit trail…</div> : activity.isError ? <div className="p-12 text-center"><p className="text-sm text-rose-700">Project activity could not be loaded.</p><Button className="mt-3" size="sm" variant="outline" onClick={() => activity.refetch()}>Retry activity</Button></div> : activity.data?.length ? activity.data.map(event => <div key={event.id} className="grid grid-cols-[1.2fr_1fr_auto] items-center gap-3 border-b border-slate-100 px-5 py-4 last:border-0"><div><p className="text-sm font-medium">{event.action}</p><p className="mt-1 text-xs text-slate-500">{event.detail || "No additional detail"}</p></div><span className="text-xs text-slate-500">{new Date(event.createdAt).toLocaleString()}</span><Badge variant="outline" className="justify-self-end font-mono text-[10px]">{event.outcome}</Badge></div>) : <div className="p-14 text-center"><FolderGit2 className="mx-auto size-6 text-slate-300" /><p className="mt-3 font-semibold">No lifecycle events yet</p><p className="mt-1 text-sm text-slate-500">Project creation, edits, and deletion actions are recorded here once they occur.</p></div>;
  return <div className="mx-auto max-w-[1100px] space-y-6"><section className="blueprint-card relative overflow-hidden p-7 sm:p-9"><div className="absolute right-10 top-10 size-28 rotate-45 border border-cyan-200" /><div className="relative max-w-2xl"><span className="flex size-11 items-center justify-center rounded-2xl bg-cyan-100 text-cyan-900"><History className="size-5" /></span><p className="eyebrow mt-6">OWNERSHIP-SCOPED PROJECT TRACE</p><h1 className="mt-2 text-4xl font-black tracking-[-0.055em] text-slate-950">Project activity</h1><p className="mt-4 text-sm leading-6 text-slate-600">Review lifecycle events for one owned project. The view is limited to the active account and never exposes records from another workspace.</p></div></section><Card className="blueprint-card border-0"><CardContent className="p-6"><div className="max-w-md space-y-2"><Label>Project</Label>{projects.isLoading ? <div className="h-10 animate-pulse rounded-md bg-slate-100" /> : projects.data?.length ? <Select value={projectId} onValueChange={setProjectId}><SelectTrigger><SelectValue placeholder="Select a project" /></SelectTrigger><SelectContent>{projects.data.map(project => <SelectItem key={project.id} value={String(project.id)}>{project.name}</SelectItem>)}</SelectContent></Select> : <p className="rounded-md border border-dashed border-slate-200 p-3 text-sm text-slate-500">No owner-scoped projects are available yet.</p>}</div></CardContent></Card><Card className="blueprint-card border-0"><CardContent className="p-0"><div className="grid grid-cols-[1.2fr_1fr_auto] border-b border-slate-200 bg-slate-50/70 px-5 py-3 font-mono text-[10px] uppercase tracking-[0.12em] text-slate-500"><span>Event</span><span>Recorded</span><span>Outcome</span></div>{activityBody}</CardContent></Card></div>;
}
